name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: "Build Docker image"
    outputs:
      tag_deploy: ${{ steps.tag_deploy.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Semantic Release (Dry Run)
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          tag_format: ${version}
          branches: |
            [ 'main' ]
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/release-notes-generator@12.1.0
            @semantic-release/git@10.0.1
            @semantic-release/github@9.2.6
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gradle Properties
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i -e "s/version=.*/version=${{ steps.semantic.outputs.new_release_version }}/g" gradle.properties

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: petretiandrea/poke-poke
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ steps.semantic.outputs.new_release_version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          tag_format: ${version}
          branches: |
            [ 'main' ]
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/release-notes-generator@12.1.0
            @semantic-release/git@10.0.1
            @semantic-release/github@9.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}